# --------- CONFIG FILE -------- #
CONFIG_FILE = "config.ini"
# ---------- SETTINGS ---------- #
SETTINGS_SECTION = "GlobalSettings"
IMPORT_TRANSACTIONS_FIELD = "import-transactions"
IMPORT_TRANSACTIONS_DEFAULT = "True"
IMPORT_ACCOUNTS_FIELD = "import-accounts"
IMPORT_ACCOUNTS_DEFAULT = "True"
IMPORT_ACCOUNT_ID_LIST_FIELD = "import-account-ids-list"
IMPORT_ACCOUNT_ID_LIST_DEFAULT = "XXXXXXXXXXX,XXXXXXXXXXX,XXXXXXXXXXX"
# --------- CREDENTIALS -------- #
CREDENTIALS_SECTION = "CreditAgricole"
BANK_REGION_FIELD = "bank-region"
BANK_REGION_DEFAULT = "paris"
BANK_ACCOUNT_ID_FIELD = "bank-account-id"
BANK_ACCOUNT_ID_DEFAULT = "XXXXXXXXXXX"
BANK_PASSWORD_FIELD = "bank-password"
BANK_PASSWORD_DEFAULT = "XXXXXX"
# ----------- FIREFLY ---------- #
FIREFLY3_SECTION = "FireflyIII"
URL_FIELD = "url"
URL_DEFAULT = "https://demo.firefly-iii.org/"
PERSONAL_TOKEN_FIELD = "personal-token"
PERSONAL_TOKEN_DEFAULT = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"